### ISSUE TITLE
Add "I can't believe it can sort" sort?

### ISSUE THREAD

**Issue by mentalisttraceur** [insolitum/sorting_algos#7]
Might be fun to add the "I can't believe it can sort" sort from https://arxiv.org/abs/2110.01111 to the visualizer?

![tumblr_c5cda6e338f8e559e5516197041ba10a_6d669b9d_1280](https://user-images.githubusercontent.com/6531708/212449865-183a9aa0-e624-4b59-97dc-aa845bd1f52a.png)

**Comment by insolitum** [comment]
Hey, algorithm works the same way as bubble sort so I don't see the point of adding it.

**Comment by mentalisttraceur** [comment]
Yeah so people's impressions that it works "the same way" as bubble sort is the strongest argument that it's worth visualizing, actually.

Not that it's anything profound. It just works significantly less efficiently and more redundantly than bubble sort, with a lot of counterproductive motions - so the value is "oh, I didn't realize how much effort it wasted" and/or "neat how all those wrong actions eventually cancelled themselves out". Fun to see once or twice and show people sometimes.
